# 四、创建app

### 4.1 创建apps文件夹

**回到根目录**

`mkdir apps`

**进入apps文件夹**

`cd apps`

### 4.2 新建app

**创建app代码**

```python
python ../manage.py startapp test1(app名字)
```

**查看创建文件**

```python
>>>tree
.
└── test1
    ├── admin.py
    ├── apps.py
    ├── __init__.py
    ├── migrations
    │   └── __init__.py
    ├── models.py
    ├── tests.py
    └── views.py

2 directories, 7 files
```

#### 出现过的问题

##### 1.未进入虚拟环境

```python
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

如果整个文件是在虚拟环境中的，那就必须先进入虚拟环境即：`workon 环境名`。然后再使用上面的命令

##### 2. 其余的文件夹命名错误

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.8/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/summer/DjangoTest/logs/DT.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../manage.py", line 22, in <module>
    main()
  File "../manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/summer/.virtualenvs/DjangoModel/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/summer/.virtualenvs/DjangoModel/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/summer/.virtualenvs/DjangoModel/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/summer/.virtualenvs/DjangoModel/lib/python3.8/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
```

上面的错误是应为再之前创建日志文件时，使用了log作为文件名，这与python中的一些文件会重名导致出现错误，因此在创建的log文件夹需要加其他东西，例如：`logs`

### 4.3配置settings

在INSERT_APP下加入：`'apps.test1',`

当然可以按照下面的方式一劳永逸：

```python
import sys

# 创建应用之后，把apps目录加入到sys.path中
sys.path.insert(0, BASE_DIR)
sys.path.insert(1, os.path.join(BASE_DIR, 'apps'))

```

### 4.4配置url

#### 1)在test1中创建url

```python
# 现在test1这个app里面新建一个urls.py

from django.urls import path

urlpatterns = []
```

#### 2)在总url中添加app路由

```python
from django.urls import include, path

urlpatterns = [
    path('test1/', include('test1.urls')), # 这里加什么，那么在8000后面就需要添加什么
]
```

### 4.5 添加测试视图

1)在test1的views.py内创建：

```python
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def demo(request):
	res = "这是一个测试app视图"
	return HttpResponse(res)
```

2)回到test1/urls.py，添加视图的路由

```python
from django.urls import path
from . import views

app_name = "demo"

urlpatterns = [
	path('demo', views.demo),
]
```

### 4.6测试

启动django,然后再地址栏输入:`127.0.0.1:8000/test1/demo`或者`127.0.0.1:8000/test1/demo/`这个横杠取不取去决议test1/urls.py下面的path内部是否添加`/`。如果加了就必须写，如果没加即可不写。

### 4.7 遇到的问题

#### 1.路径错误

再写url的时候，一定要注意格式：

```python
urlpatterns = [
	path('demo', views.demo),
]
```

这个path不能省略

#### 2.RuntimeError: cryptography is required for sha256_password or caching_sha2_password

这个比较简单，直接下载即可，问题还是一样，必须在虚拟环境内下载：

`pip install cryptography `